apiVersion: v1
kind: Service
metadata:
  name: configuration-service
  namespace: etax-viriyah
  labels:
    app: configuration-service
spec:
  ports:
    - port: 8080
      targetPort: 8080
      name: http
  selector:
    app: configuration-service
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: configuration-service
  namespace: etax-viriyah
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: configuration-service
  namespace: etax-viriyah
  labels:
    app: configuration-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: configuration-service
  template:
    metadata:
      labels:
        app: configuration-service
    spec:
      serviceAccountName: configuration-service
      containers:
        - image: ${CICD_IMAGE}:${CICD_GIT_TAG}
          imagePullPolicy: IfNotPresent
          name: configuration-service
          ports:
            - containerPort: 8080
              protocol: TCP
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: k8s-dev
            - name: APP_NAME
              value: configuration-service
            - name: TZ
              value: Asia/Bangkok
            - name: MY_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NAME_SPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: CONFIG_POSTGRES_URL
              valueFrom:
                configMapKeyRef:
                  name: etax-config
                  key: CONFIG_POSTGRES_URL
            - name: CONFIG_POSTGRES_PORT
              valueFrom:
                configMapKeyRef:
                  name: etax-config
                  key: CONFIG_POSTGRES_PORT
            - name: CONFIG_POSTGRES_SCHEMA
              valueFrom:
                configMapKeyRef:
                  name: etax-config
                  key: CONFIG_POSTGRES_SCHEMA
            - name: SECRET_POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: etax-secret
                  key: DB_USER
            - name: SECRET_POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: etax-secret
                  key: DB_PASSWORD
      imagePullSecrets:
        - name: gitlab